security:
    # Enable authenticator manager
    enable_authenticator_manager: true
    
    # Configure the password hasher
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # Providers define how users are loaded
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls define how your users will authenticate
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout

    # Access control defines which parts of your site users can access
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

    # Role hierarchy
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER