<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZafQ288\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZafQ288/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZafQ288.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZafQ288\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZafQ288\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZafQ288',
    'container.build_id' => 'd20cb8a3',
    'container.build_time' => 1749376951,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZafQ288');
